adds kick hardware challenge rule
robocup-ssl-br/rules-technical-challenge-el pull request #2
Opened 2024-05-01 22:05 UTC by PedroPizarro

Adicionar as regras do desafio técnico de chute com robôs adversários estáticos. 
Esse TC visa incentivar as equipes do SSL-EL a desenvolverem o sistema de chute.

2024-05-01 22:07 UTC, PedroPizarro commented
@ersaraujo @JoaoVictor0508 Novamente a dúvida, os cenários ficaram decidios que vão somente ser mostrados na hora? Não coloquei nada no apêndice.

2024-05-05 17:54 UTC, JoaoVictor0508 commented on 2024/2024-ssl-el-kick-rules.adoc
> +* The team may change its trail robot during the challenge in between trails.
```suggestion
* The team may change its robot during the challenge in between trials.
```

2024-05-05 17:54 UTC, JoaoVictor0508 commented on 2024/2024-ssl-el-kick-rules.adoc
> +* There will be two members of OC, TC and EC that will act as the supervisors of the challenges.
```suggestion
* There will be two TC/OC/EC members that will act as the supervisors of the challenges.
```

2024-05-05 17:54 UTC, JoaoVictor0508 commented on 2024/2024-ssl-el-kick-rules.adoc
> +== Challenge
Duplicated 😄

2024-05-14 19:11 UTC, ersaraujo requested changes
Waiting for scenarios and modifications suggested.

2024-05-19 23:48 UTC, PedroPizarro commented
> Waiting for scenarios and modifications suggested.

Just added the scenarios on my last commit.

2024-08-07 00:23 UTC, ersaraujo approved these changes

2024-08-07 12:01 UTC, JoaoVictor0508 approved these changes

2024-08-07 12:14 UTC, merged