adds new rules about  the robot placement technical challenge
robocup-ssl-br/rules-technical-challenge-el pull request #3
Opened 2024-05-02 22:52 UTC by fabiooju

This is the new rules from robot placement technical challenge, including the procedure, evaluation, socring and tiebreak criteria. According to the league's objectives, this technical challenge will motivate the automatic positioning of the robots, aiming for compliance with the regular league.

2024-05-05 17:33 UTC, JoaoVictor0508 commented on 2024/2024-ssl-el-robot-placement.adoc
> +3. Colliding with obstacles during the placement — -1
Just to be clear, "obstacles" are the "opponent robots" that will be placed in the scenarios, right?

2024-05-05 17:33 UTC, JoaoVictor0508 commented on 2024/2024-ssl-el-robot-placement.adoc
> +2. Colliding with a robot during the placement — -1 (just one robot loses points)
```suggestion
2. Colliding with a team robot during the placement — -1

```

2024-05-05 17:33 UTC, JoaoVictor0508 commented on 2024/2024-ssl-el-robot-placement.adoc
> +
```suggestion

NOTE: A collision between two or more team robots will count as one collision, i.e., the collision will cost -1 for the team, not -1 for each robot.
```

2024-05-05 17:33 UTC, JoaoVictor0508 commented on 2024/2024-ssl-el-robot-placement.adoc
> +2. Free Kick
Are we going to consider the ball in the scenarios too? If so, the ball will be considered as an obstacle for the Scoring?

2024-05-14 19:19 UTC, ersaraujo requested changes

2024-05-14 19:19 UTC, ersaraujo commented on 2024/2024-ssl-el-robot-placement.adoc
> +== Start
I believe that `Start` and `Goal` are subtopics of `scenarios`, right?
I think they both should be at a higher title level. ie
```
=== Scenarios.
==== Start
==== Goal
```

2024-05-14 19:19 UTC, ersaraujo commented on 2024/2024-ssl-el-robot-placement.adoc
> +== Start
I believe that `Start` and `Goal` are subtopics of `scenarios`, right?
I think they both should be at a higher title level. ie
```
=== Scenarios.
==== Start
==== Goal
```

2024-05-14 19:19 UTC, ersaraujo commented on 2024/2024-ssl-el-robot-placement.adoc
> +== Start
I believe that `Start` and `Goal` are subtopics of `scenarios`, right?
I think they both should be at a higher title level. ie
```
=== Scenarios.
==== Start
==== Goal
```

2024-05-14 19:19 UTC, ersaraujo commented on 2024/2024-ssl-el-robot-placement.adoc
> +== Start
I believe that `Start` and `Goal` are subtopics of `scenarios`, right?
I think they both should be at a higher title level. ie
```
=== Scenarios.
==== Start
==== Goal
```

2024-08-07 00:24 UTC, ersaraujo approved these changes

2024-08-07 12:01 UTC, JoaoVictor0508 approved these changes

2024-08-07 12:14 UTC, merged